### ISSUE TITLE
lollolman isnt banned

### ISSUE THREAD

**Issue by thereallollolman** [typicalname0/spacemy.xyz#21]
thats a problem

**Comment by pizzaboxer** [comment]
shut the fuck up

**Comment by thereallollolman** [comment]
no you

**Comment by ezist** [comment]
shut the fuck up

**Comment by typicalname0** [comment]
literal retard

**Comment by nxm3** [comment]
dude just ban him, he is ANNOYING

**Comment by ezist** [comment]
That's up to typical to decide, I have no access to the website's database
