### ISSUE TITLE
serious bug with comments

### ISSUE THREAD

**Issue by lollolman2** [typicalname0/spacemy.xyz#23]
theres no One cold night.
    There were to people that didn't know they were meant with each other.
    Their names were Ryelow and Dreamer
    one day they met up and Ryelow made Ryelow 2, with Dreamer as an ryelow.ml admin.
    They didn't know that they were getting closer friends. Maybe they're even getting closer than that.
 
    --Dreamer'S PERSPECTIVE--
    I felt cold and alone. i had no friends. Had. now i have Ryelow. i feel like hes more of a friend. i'm not telling him that i think that, though. How we met was simple. Finobe Discord. In Early 2019, Ryelow made Ryelow 2, and I was invited to it. I made some CRINGY videos with it, and we started becoming friends. Now we skip to 2016. I wanna fuck him.
 
    --Ryelow'S PERSPECTIVE--
    He looked alone. His server was filled with new users that are doomed to never come back. I had friends, and I think he was another friend that I could make. He's... hot. I mean.. don't you look at that ass and want to bit-- oh.. sorry about that. I'm attracted. Sex. Now.
 
    --3RD PERSON--
    Dreamer had enough, he was going to tell Ryelow the truth. He loved him. He didn't know that Ryelow loved him, too. Ryelow was unprepared for this moment.
 
    --Ryelow'S HOUSE, 9:24 PM AT NIGHT--
    Dreamer knock's on Ryelow's door. Ryelow answers, rudely interrupted from his Ryelow.ml site development. "Hey, Ryelow." mumbled Dreamer. "I need to tell you something."
    "One moment," replied Ryelow. Ryelow goes into his house to close ryelow.ml for a bit. Then he comes back out. "What is it that you need to tell me?"
    "Well, can I come in?" asked Dreamer nervously.
    "S-Sure.." answered Ryelow, unsure.
    "S-so b-basically.. I'm in m-mad love with you." Dreamer said slowly. Ryelow went red.
    "I..." said Ryelow trying to reply.
    "You can stay away from me, I'll understand." replied Dreamer
    "N-No.. I feel the same.." Ryelow said, red and nervous.
    "Hehe.. you're cute.." Dreamer teased.
    "I WANT TO HA-" Ryelow stopped himself. Dreamer knew what he was going to say. Dreamer would gladly accept if he finished the thought.
    "Go on..." said Dreamer.
    "h-have.... s-s-ex" Ryelow is the reddest of reds right now.
    "With who?" replied Dreamer, who was confident to get Ryelow under the sheets.
    "D-Dreamer" Ryelow finally finished.
    "Lets go to the bed, cute one." Said Dreamer.
    --THE BEDROOM--
    They wouldn't speak. They were ready. Ryelow was laid on the bed by Dreamer. They began kissing. Ryelow reached under Dreamer's pants. Dreamer was already hard. Dreamer was just the right size to turn Ryelow on. Ryelow was ready to be taken by the iFunny memer.
    "Dreamer," Ryelow asked "can you fuck me as hard as you can?" Dreamer chuckled, and nodded. Dreamer undressed Ryelow, then undressed himself.
Dreamer was going in. Dreamer inserted his dick into Ryelow slowly. Ryelow started to moan
    "A-ah.. yes.. oh fuck.." Dreamer could see that Ryelow was enjoying him. Dreamer goes faster. Ryelow is having the time of his life. Ryelow had his dream achieved, fucked silly by Dreamer. After hours of fucking, Dreamer came in Ryelow's tight ass.
    Ryelow cleaned up in the bathroom first.
    "Holy fuck. we need to do that again." Ryelow talked to himself. After cleansing, Dreamer went in and washed up. They both sleeped together, hugging.
   
    Written by dreamer
   
   
   
    -dreamer 15/8/2019 19:45 limit

**Comment by pizzaboxer** [comment]
shut the fuck UP

**Comment by lollolman2** [comment]
i was going to say theres no rate limit but i thought this would be funny

**Comment by ezist** [comment]
You're fucking retarded, my man

**Comment by nxm3** [comment]
and you wonder why no one likes you

**Comment by aarexfletcher** [comment]
![mUMLcw](https://user-images.githubusercontent.com/68448002/88779486-d5f22e80-d157-11ea-9936-72c55e1cc7fd.gif) A NIGGER WALKS INTO A STORE.............. STEALAS SHOES LMAO

**Comment by IHATENIGGERS232** [comment]
> ![mUMLcw](https://user-images.githubusercontent.com/68448002/88779486-d5f22e80-d157-11ea-9936-72c55e1cc7fd.gif) A NIGGER WALKS INTO A STORE.............. STEALAS SHOES LMAO

**Comment by Niggersblack23** [comment]
> > ![mUMLcw](https://user-images.githubusercontent.com/68448002/88779486-d5f22e80-d157-11ea-9936-72c55e1cc7fd.gif) A NIGGER WALKS INTO A STORE.............. STEALAS SHOES LMAO
