### ISSUE TITLE
image size on friend requests and friends lists

### ISSUE THREAD

**Issue by krmeet** [typicalname0/spacemy.xyz#25]
on friend requests the image will always stretch the size of the box to fit the size of the image
on friends list the image will commonly be tiled in the down or right direction

**Comment by pizzaboxer** [comment]
probably has something to do with the way we do grids

**Comment by krmeet** [comment]
i think you just need to add width and height parameter on the friend requests

**Comment by DerekChauvinFanboy** [comment]
Then fix it you fucking nigger

**Comment by FuckNiggersIHateThem707** [comment]
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68985358/88885951-dbab4b00-d20f-11ea-8c75-1aeed205b51c.gif)
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/68985358/88885954-dd750e80-d20f-11ea-9b1d-38c7aa7c0537.gif)
![tflag2](https://user-images.githubusercontent.com/68985358/88886113-2cbb3f00-d210-11ea-93a3-6a007221f25a.gif)
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/68985358/88886121-32188980-d210-11ea-953e-982a4553269a.gif)

**Comment by FuckNiggersIHateThem707** [comment]
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68985358/88885951-dbab4b00-d20f-11ea-8c75-1aeed205b51c.gif)
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/68985358/88885954-dd750e80-d20f-11ea-9b1d-38c7aa7c0537.gif)
![tflag2](https://user-images.githubusercontent.com/68985358/88886113-2cbb3f00-d210-11ea-93a3-6a007221f25a.gif)
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/68985358/88886121-32188980-d210-11ea-953e-982a4553269a.gif)

**Comment by FuckNiggersIHateThem707** [comment]
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68985358/88885951-dbab4b00-d20f-11ea-8c75-1aeed205b51c.gif)
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/68985358/88885954-dd750e80-d20f-11ea-9b1d-38c7aa7c0537.gif)
![tflag2](https://user-images.githubusercontent.com/68985358/88886113-2cbb3f00-d210-11ea-93a3-6a007221f25a.gif)
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/68985358/88886121-32188980-d210-11ea-953e-982a4553269a.gif)

**Comment by FuckNiggersIHateThem707** [comment]
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68985358/88885951-dbab4b00-d20f-11ea-8c75-1aeed205b51c.gif)
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/68985358/88885954-dd750e80-d20f-11ea-9b1d-38c7aa7c0537.gif)
![tflag2](https://user-images.githubusercontent.com/68985358/88886113-2cbb3f00-d210-11ea-93a3-6a007221f25a.gif)
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/68985358/88886121-32188980-d210-11ea-953e-982a4553269a.gif)
