### ISSUE TITLE
clean up page organization

### ISSUE THREAD

**Issue by pizzaboxer** [typicalname0/spacemy.xyz#29]
its kinda a mess rn

to explain what i'm talking about, take all the group-related pages in the root directory
`/groups.php`
`/viewgroup.php`
`/joingroup.php`
`/leavegroup.php`
`/newgroup.php`

these are all in the root and it just seems rather cluttered doesnt it
i mean just look at this:
![](https://cdn.discordapp.com/attachments/377894067712950275/734895390352212049/explorer_IKwbTdkrtS.png)

so what we should probably do soon is better organize it
for example
`/groups.php` -> `/groups/`
`/viewgroup.php` -> `/groups/view.php`
`/joingroup.php` -> `/groups/join.php`
`/leavegroup.php` -> `/groups/leave.php`
`/newgroup.php` -> `/groups/new.php`

exact same thing can also be appled to blogs and friends

**Comment by aarexfletcher** [comment]
NO NO NO THIS WILL MEAN MORE NIGGERS WE CAN'T DO THIS. DISCUSSION OVER

**Comment by IHATENIGGERS232** [comment]
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68945465/88778822-59634e00-d15f-11ea-9708-f2c2d4f02ca1.gif)
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/68945465/88778835-5c5e3e80-d15f-11ea-9d9e-0e2245c7ae4b.gif)
NIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGER
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68945465/88778822-59634e00-d15f-11ea-9708-f2c2d4f02ca1.gif)
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/68945465/88778835-5c5e3e80-d15f-11ea-9d9e-0e2245c7ae4b.gif)
NIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGERNIGGER

**Comment by Niggersblack23** [comment]
Added nige

**Comment by IHATENIGGERS232** [comment]
![6x6prEyMQHq4LliAZuRy_photo](https://user-images.githubusercontent.com/68945465/88779184-da224a00-d15f-11ea-8dd2-629289d5811b.jpg)

**Comment by IHATENIGGERS232** [comment]
![6x6prEyMQHq4LliAZuRy_photo](https://user-images.githubusercontent.com/68945465/88779184-da224a00-d15f-11ea-8dd2-629289d5811b.jpg)

**Comment by IHATENIGGERS232** [comment]
![6x6prEyMQHq4LliAZuRy_photo](https://user-images.githubusercontent.com/68945465/88779184-da224a00-d15f-11ea-8dd2-629289d5811b.jpg)

**Comment by IHATENIGGERS232** [comment]
> ![mUMLcw](https://user-images.githubusercontent.com/68448002/88779486-d5f22e80-d157-11ea-9936-72c55e1cc7fd.gif) A NIGGER WALKS INTO A STORE.............. STEALAS SHOES LMAO

**Comment by SHOESTEALER123** [comment]
A NIGGER WALKS INTO A STORE.............. STEALAS SHOES LMAO

**Comment by IHATENIGGERS232** [comment]
NIGGER

**Comment by FuckNiggersIHateThem707** [comment]
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/68985358/88886121-32188980-d210-11ea-953e-982a4553269a.gif)
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68985358/88885951-dbab4b00-d20f-11ea-8c75-1aeed205b51c.gif)
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/68985358/88885954-dd750e80-d20f-11ea-9b1d-38c7aa7c0537.gif)
![tflag2](https://user-images.githubusercontent.com/68985358/88886113-2cbb3f00-d210-11ea-93a3-6a007221f25a.gif)

**Comment by FuckNiggersIHateThem707** [comment]
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/68985358/88886121-32188980-d210-11ea-953e-982a4553269a.gif)
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68985358/88885951-dbab4b00-d20f-11ea-8c75-1aeed205b51c.gif)
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/68985358/88885954-dd750e80-d20f-11ea-9b1d-38c7aa7c0537.gif)
![tflag2](https://user-images.githubusercontent.com/68985358/88886113-2cbb3f00-d210-11ea-93a3-6a007221f25a.gif)

**Comment by FuckNiggersIHateThem707** [comment]
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/68985358/88886121-32188980-d210-11ea-953e-982a4553269a.gif)
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68985358/88885951-dbab4b00-d20f-11ea-8c75-1aeed205b51c.gif)
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/68985358/88885954-dd750e80-d20f-11ea-9b1d-38c7aa7c0537.gif)
![tflag2](https://user-images.githubusercontent.com/68985358/88886113-2cbb3f00-d210-11ea-93a3-6a007221f25a.gif)

**Comment by FuckNiggersIHateThem707** [comment]
![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/68985358/88886121-32188980-d210-11ea-953e-982a4553269a.gif)
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68985358/88885951-dbab4b00-d20f-11ea-8c75-1aeed205b51c.gif)
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/68985358/88885954-dd750e80-d20f-11ea-9b1d-38c7aa7c0537.gif)
![tflag2](https://user-images.githubusercontent.com/68985358/88886113-2cbb3f00-d210-11ea-93a3-6a007221f25a.gif)
