### ISSUE TITLE
Registration error on line 36, WTF?

### ISSUE THREAD

**Issue by Niggersblack23** [typicalname0/spacemy.xyz#48]
i was just using the site and then it said NIGGER NIGGERS ARE BLACK: Var on line 36 and then like george floyd came out of the screen like fix your racist ass site

**Comment by Niggersblack23** [comment]
What a nigger site

**Comment by johnfortnitekennedyCorp** [comment]
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/68939829/88777769-fb823680-d15d-11ea-9203-187fe1c636f8.gif)
