### ISSUE TITLE
EZIST NEDS TO FIX NIGGERS

### ISSUE THREAD

**Issue by aarexfletcher** [typicalname0/spacemy.xyz#74]
TOO MANY NIGGERS...... TOO MANY PROBLEMS...... FIX IT NOW!

**Comment by IHATENIGGERS232** [comment]
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68945465/88777417-929abe80-d15d-11ea-857b-17f2847d1684.gif)

**Comment by IHATENIGGERS232** [comment]
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68945465/88777417-929abe80-d15d-11ea-857b-17f2847d1684.gif)
