### ISSUE TITLE
CLEAN UP NIGGERS

### ISSUE THREAD

**Issue by aarexfletcher** [typicalname0/spacemy.xyz#76]
SWEEP SWEEP GOTTA CLEAN UP THESE NIGGERS

**Comment by johnfortnitekennedyCorp** [comment]
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68945465/88777417-929abe80-d15d-11ea-857b-17f2847d1684.gif)

**Comment by Niggersblack23** [comment]
CLEAN THOSE NIGGERS UP GET TAHEM OUT

**Comment by johnfortnitekennedyCorp** [comment]
![d27f22473dd357c3e081baf3bdc596a13b26c7e8_full](https://user-images.githubusercontent.com/68939829/88777701-e5747600-d15d-11ea-9743-a2ea5c212a0f.jpg)

**Comment by lighterlightbulb** [comment]
Ummm... No racism please

**Comment by Niggersblack23** [comment]
GOTTA SWEEP SWEEP SWEEP THOSE NIGGER AWAY

**Comment by johnfortnitekennedyCorp** [comment]
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/68945465/88777417-929abe80-d15d-11ea-857b-17f2847d1684.gif)

**Comment by johnfortnitekennedyCorp** [comment]
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/68939829/88777769-fb823680-d15d-11ea-9203-187fe1c636f8.gif)

**Comment by johnfortnitekennedyCorp** [comment]
ME WHEN I SEE A NIGGER
