### ISSUE TITLE
Going tob![tenor](https://user-images.githubusercontent.com/68448002/88778042-fb7e3880-d155-11ea-8cd7-83f4e36c306f.gif)

### ISSUE THREAD

**Issue by Niggersblack23** [typicalname0/spacemy.xyz#80]
![tenor](https://user-images.githubusercontent.com/68448002/88778042-fb7e3880-d155-11ea-8cd7-83f4e36c306f.gif)
Going to bed

_Originally posted by @aarexfletcher in https://github.com/typicalname0/spacemy.xyz/issues/79#issuecomment-665526067_

**Comment by IHATENIGGERS232** [comment]
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/68945465/88777966-41d79580-d15e-11ea-8c0c-4be5759eb9d0.gif)
NIGGERS BE LIKE
